### ISSUE TITLE
utf8 input is not supported

### ISSUE THREAD

**Issue by thefab** [andreasjansson/envtpl#18]
utf8 encoded templates files are not supported

example:

```bash
(envtpl)[root@a609b96871ce ~]# echo "ééé" |envtpl 
Traceback (most recent call last):
  File "/opt/envtpl/bin/envtpl", line 9, in <module>
    load_entry_point('envtpl==0.5.0', 'console_scripts', 'envtpl')()
  File "/opt/envtpl/lib/python2.6/site-packages/envtpl.py", line 53, in main
    process_file(args.input_file, args.output_file, variables, not args.allow_missing, not args.keep_template)
  File "/opt/envtpl/lib/python2.6/site-packages/envtpl.py", line 79, in process_file
    output = _render_string(sys.stdin.read(), variables, undefined)
  File "/opt/envtpl/lib/python2.6/site-packages/envtpl.py", line 93, in _render_string
    return _render(template_name, loader, variables, undefined)
  File "/opt/envtpl/lib/python2.6/site-packages/envtpl.py", line 105, in _render
    template = env.get_template(template_name)
  File "/opt/envtpl/lib/python2.6/site-packages/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/opt/envtpl/lib/python2.6/site-packages/jinja2/environment.py", line 786, in _load_template
    template = self.loader.load(self, name, globals)
  File "/opt/envtpl/lib/python2.6/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/opt/envtpl/lib/python2.6/site-packages/jinja2/environment.py", line 551, in compile
    source = self._parse(source, name, filename)
  File "/opt/envtpl/lib/python2.6/site-packages/jinja2/environment.py", line 470, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/opt/envtpl/lib/python2.6/site-packages/jinja2/parser.py", line 31, in __init__
    self.stream = environment._tokenize(source, name, filename, state)
  File "/opt/envtpl/lib/python2.6/site-packages/jinja2/environment.py", line 501, in _tokenize
    source = self.preprocess(source, name, filename)
  File "/opt/envtpl/lib/python2.6/site-packages/jinja2/environment.py", line 495, in preprocess
    self.iter_extensions(), text_type(source))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)
```

**Comment by andreasjansson** [comment]
Yikes, thanks for reporting this, I'll look into it!

**Comment by andreasjansson** [comment]
Fixed in https://github.com/andreasjansson/envtpl/commit/de4997b98ab3b5058da5007e08372893571d9d4d
