### ISSUE TITLE
Wrong enconding while writting to the file

### ISSUE THREAD

**Issue by pelid** [andreasjansson/envtpl#20]
If I specify output file with option `-o` - script fails with traceback: 

```
envtpl -o nginx.conf < nginx.tmpl.conf
Traceback (most recent call last):
  File "/opt/platform/pyenv/bin/envtpl", line 11, in <module>
    sys.exit(main())
  File "/opt/platform/pyenv/lib/python3.5/site-packages/envtpl.py", line 56, in main
    not args.allow_missing, not args.keep_template)
  File "/opt/platform/pyenv/lib/python3.5/site-packages/envtpl.py", line 89, in process_file
    f.write(output)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 2-9: ordinal not in range(128)
```

but if STDOUT redirection is used instead - everything is OK :

```
envtpl < nginx.tmpl.conf > nginx.conf
```

I suppose there is a bug.

**Comment by hardware** [comment]
Same bug here : https://github.com/hardware/mailserver/issues/118

```
Traceback (most recent call last):
  File "/usr/local/bin/envtpl", line 9, in <module>
    load_entry_point('envtpl==0.5.3', 'console_scripts', 'envtpl')()
  File "/usr/local/lib/python2.7/dist-packages/envtpl.py", line 56, in main
    not args.allow_missing, not args.keep_template)
  File "/usr/local/lib/python2.7/dist-packages/envtpl.py", line 89, in process_file
    f.write(output)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xb0' in position 55: ordinal not in range(128)
```

Maybe a solution -> https://stackoverflow.com/a/9942822 ?

**Comment by purplesrl** [comment]
+1

Workaround, replace 

f.write(output) with:

f.write(output.encode('utf-8'))

**Comment by andreasjansson** [comment]
I think this is fixed now in https://github.com/andreasjansson/envtpl/pull/25, if not please let me know and I'll reopen.
