### ISSUE TITLE
envtpl does not support utf-8 

### ISSUE THREAD

**Issue by haithem2** [andreasjansson/envtpl#22]
Hello,

I use envtpl to Render jinja2 templates but I note that this tool can't create file from *.tpl file that was encoded in UTF-8:

Traceback (most recent call last):
  File "/usr/local/bin/envtpl", line 9, in <module>
    load_entry_point('envtpl==0.5.3', 'console_scripts', 'envtpl')()
  File "/usr/local/lib/python2.7/dist-packages/envtpl.py", line 56, in main
    not args.allow_missing, not args.keep_template)
  File "/usr/local/lib/python2.7/dist-packages/envtpl.py", line 89, in process_file
    f.write(output)
"UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 1499: ordinal not in range(128)  =====> é

Could you check please ?

**Comment by dreambeam** [comment]
@haithem2  I came across the same error.
Thought the workaround described by @purplesrl [link](https://github.com/andreasjansson/envtpl/issues/20) works something needs to be done at the code level. 

Traceback (most recent call last):
  File "/usr/local/bin/envtpl", line 9, in <module>
    load_entry_point('envtpl==0.5.3', 'console_scripts', 'envtpl')()
  File "/usr/local/lib/python2.7/dist-packages/envtpl.py", line 56, in main
    not args.allow_missing, not args.keep_template)
  File "/usr/local/lib/python2.7/dist-packages/envtpl.py", line 89, in process_file
    f.write(output)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u201d' in position 3073: ordinal not in range(128)

**Comment by haithem2** [comment]
thx I will check

**Comment by andreasjansson** [comment]
This should be fixed in https://github.com/andreasjansson/envtpl/pull/25 -- thanks again @haithem2
